"""made diagnosis nullable

Revision ID: 8442278bdf66
Revises: 3589edefe4eb
Create Date: 2026-02-15 22:08:59.303305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8442278bdf66'
down_revision: Union[str, Sequence[str], None] = '3589edefe4eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cases', 'diagnosis',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cases', 'diagnosis',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
